export const SPA_IMAGES = {
  hero:            "/images/spa/hero.jpg",
  heroPortrait:    "/images/spa/hero-portrait.jpg",
  about:           "/images/spa/about.jpg",
  aboutSecondary:  "/images/spa/about-secondary.jpg",
  swedish:         "/images/spa/service-swedish.jpg",
  deepTissue:      "/images/spa/service-deep-tissue.jpg",
  aromatherapy:    "/images/spa/service-aromatherapy.jpg",
  hotStone:        "/images/spa/service-hot-stone.jpg",
  reflexology:     "/images/spa/service-reflexology.jpg",
  couples:         "/images/spa/service-couples.jpg",
  ctaBanner:       "/images/spa/cta-banner.jpg",
  booking:         "/images/spa/booking.jpg",
  contact:         "/images/spa/contact.jpg",
} as const;
